#!/usr/bin/env node

var sleep = require('sleep');
var Sound = require('node-aplay');

var precision = 0.001; // Seconds
var offset = -800; // Millisecond

function beep (time) {
    if (time == 1000)
    {
        new Sound('beep1000.wav').play();

    }
    else if ( time == 5000 )
    {
        new Sound('beep5000.wav').play();
        //console.log("Current time is " + Date.now());
    }
    else {} // Does nothing
}

while (true)
{
  var unixMillis = Date.now();

  unixMillis = unixMillis + offset;

  var unixSecond = Math.floor(unixMillis/1000);
  var unixFakeMillis = unixSecond*1000;
  var unixFakeMillisPrecisionMinutes = Math.floor(unixSecond/60)*1000 * 60;

  var alreadyDid = false;

  if ( (unixMillis - unixFakeMillis) < precision*1000 ) // In precision
  {
    if ( alreadyDid ) // In case of system time mess up
    {
      alreadyDid = false;
      continue;
    }
    else
    {
      alreadyDid = false;

      if ( (unixMillis - unixFakeMillisPrecisionMinutes) / 1000 >= 1 )
      {
        beep (1000);
        alreadyDid = true;
        sleep.msleep(precision*1000);
      }
      else
      {
        beep (5000);
        alreadyDid = true;
        sleep.msleep(precision*1000);
      }
    }
  }
}
